services:
  database:
    ipc: host
    image: neo4j:latest
    ports:
      - 7687:7687
      - 7474:7474
    volumes:
      - $PWD/data:/data
    environment:
      - NEO4J_AUTH=${NEO4J_USERNAME-neo4j}/${NEO4J_PASSWORD-password}
      - NEO4J_PLUGINS=["apoc","graph-data-science","n10s"]
      - NEO4J_db_tx__log_rotation_retention__policy=false
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,gds.*,n10s.*
    healthcheck:
        test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider localhost:7474 || exit 1"]
        interval: 15s
        timeout: 30s
        retries: 10
    networks:
      - net

  engine:
    ipc: host
    build:
      context: .
      dockerfile: rag.Dockerfile
    volumes:
      - $PWD/share:/share
    environment:
      - NEO4J_URI=${NEO4J_URI-neo4j://database:7687}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD-password}
      - NEO4J_USERNAME=${NEO4J_USERNAME-neo4j}
    networks:
      - net
    depends_on:
      database:
        condition: service_healthy
    x-develop:
      watch:
        - action: rebuild
          path: .
          ignore:
            - rag.ipynb
            - app.py
    ports:
      - 8888:8888
      - 8501:8501
      - 28501:28501
networks:
  net: